baseURL = 'https://www.siddharthagolu.com/'
languageCode = 'en-us'
title = 'Siddhartha Golu'
theme = 'minimalist'

[outputs]
  home = ["HTML", "RSS"]

[params]
  profilePic = "/images/profile.webp"
  defaultImage = "/images/profile.webp"
  description = """
Welcome to the preferred dumping ground for my thoughts. \n\n I try to read widely across
subjects so the topics here can range from books, cinema, poetry to philosophy, machine-learning,
startups and home servers. Feel free to jump into the recent posts below, or browse through some of
[my favourites.](/tags/favourites/) \n\n

I'm usually active on<style>
  .bluesky-icon { fill: #0085ff; }
  .dark-mode .bsky-icon { fill: #ffffff; }
</style>
<svg class="bsky-icon" style="height: 1.1em; vertical-align: text-bottom; width: auto; margin-left:
2px;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640"><path d="M439.8 358.7C436.5 358.3 433.1 357.9 429.8 357.4C433.2 357.8 436.5 358.3 439.8 358.7zM320 291.1C293.9 240.4 222.9 145.9 156.9 99.3C93.6 54.6 69.5 62.3 53.6 69.5C35.3 77.8 32 105.9 32 122.4C32 138.9 41.1 258 47 277.9C66.5 343.6 136.1 365.8 200.2 358.6C203.5 358.1 206.8 357.7 210.2 357.2C206.9 357.7 203.6 358.2 200.2 358.6C106.3 372.6 22.9 406.8 132.3 528.5C252.6 653.1 297.1 501.8 320 425.1C342.9 501.8 369.2 647.6 505.6 528.5C608 425.1 533.7 372.5 439.8 358.6C436.5 358.2 433.1 357.8 429.8 357.3C433.2 357.7 436.5 358.2 439.8 358.6C503.9 365.7 573.4 343.5 593 277.9C598.9 258 608 139 608 122.4C608 105.8 604.7 77.7 586.4 69.5C570.6 62.4 546.4 54.6 483.2 99.3C417.1 145.9 346.1 240.4 320 291.1z"/></svg>
[Bluesky](https://bsky.app/profile/siddharthagolu.com).
  """
  og_image = "/images/profile.webp"

  favicon = "/favicon.png"
  favicon32 = "/favicon-32x32.png"
  favicon16 = "/favicon-16x16.png"
  appleTouchIcon = "/apple-touch-icon.png"

# Used for code highlighting
[markup]
  [markup.highlight]
    # This enables code fences (```) in markdown to be processed by Chroma
    codeFences = true
    # This is now controlled by scss theme switcher, which switches
    # between catppuccin-macchiato and catppuccin-frappe depending on the theme
    style = "catppuccin-macchiato"
    lineNos = true
    guessSyntax = true

  [markup.goldmark.renderer]
    # This enables HTML tags in markdown, used for rendering
    # the icon in the description above
    unsafe = true
